test:
  adapter: mysql2
  encoding: utf8mb4
  database: blog_development
  pool: 5
  username: root
  password: Z@kwan1234
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8mb4
  database: blog_development
  pool: 5
  username: root
  password: Z@kwan1234
  socket: /var/run/mysqld/mysqld.sock

development:
  adapter: mysql2
  encoding: utf8mb4
  database: blog_development
  pool: 5
  username: root
  password: Z@kwan1234
  socket: /var/run/mysqld/mysqld.sock
